# Урок 8

# Сингулярное разложение матриц

## Практическое задание

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найти с помощью NumPy и вручную:

    а) евклидову норму;
    
    б) норму Фробениуса.

__Решение__
__1.__

In [ ]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [ ]:
A = np.array([[1,2,0],
              [0,0, 5],
              [3,-4,2],
              [1,6,5],
             [0,1,0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [ ]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
Sigma = np.zeros_like(A, dtype=float)
Sigma[np.diag_indices(min(A.shape))] = s

In [ ]:
print(f'Матрица U:\n{U}')
print(f'Матрица Sigma:\n{Sigma}')
print(f'Матрица V:\n{V}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица Sigma:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


### Норма Евклидову 

In [ ]:
np.linalg.norm(A, ord=2)

8.824868854820444

### Норма Фробениуса

In [ ]:
(122)**(1 / 2)

11.045361017187261

In [ ]:
(8.82**2 + 6.14**2 + 2.53**2)**(1 / 2)

11.04051176350082

In [ ]:
np.linalg.norm(A, ord=None)

11.045361017187261

In [ ]:
np.linalg.norm(A, ord='fro')

11.045361017187261